changesetBaseRefs:
  - main
  - origin/main

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.5.1.cjs
