blank_issues_enabled: true
contact_links:
  - name: "🙋‍♀️ Question"
    url: https://github.com/flora-suite/flora/discussions/new?category=q-a
    about: Search discussions or ask our community for help
  - name: "🚀 Feature request"
    url: https://github.com/flora-suite/flora/discussions/new?category=ideas
    about: Search existing feature requests or share a new idea
  - name: "📚 Stack Exchange"
    url: https://robotics.stackexchange.com/questions/ask
    about: Get help from the robotics community
